#!/bin/sh

# Run this if you're using a posix compliant system.

if [ ! command -v docker > /dev/null 2>&1 ]; then
    echo "Please install docker in your system."
    exit -1
fi

# The directory where this script exists.
script_dir="$(dirname "$(readlink -f "$0")")"

# Build amd64 linux base image.
docker build -t gh-self:amd64-linux-base --build-arg RUNNER_VERSION=2.320.0 \
    --build-arg GH_PLATFORM=x64 $script_dir/linux

# Build amd64 debian image.
docker build -t gh-self:amd64-debian \
    --build-arg BUNDLE_IMAGE=gh-self:amd64-linux-base $script_dir/debian