#!/bin/sh

# Exit on error
set -e

# Check if the runner is already configured
if [ ! -f ".runner" ]; then
    # Check existence of secret files.
    if [ ! -f "/run/secrets/GITHUB_REPO_FILE" ]; then
        echo "Error: secret file not mapped to /run/secrets/GITHUB_REPO_FILE"
        exit -1
    fi
    if [ ! -f "/run/secrets/TOKEN_VALUE_FILE" ]; then
        echo "Error: secret file not mapped to /run/secrets/TOKEN_VALUE_FILE"
        exit -1
    fi

    # Extract github repository.
    GITHUB_REPO=$(cat /run/secrets/GITHUB_REPO_FILE)
    # Extract token value.
    TOKEN_VALUE=$(cat /run/secrets/TOKEN_VALUE_FILE)

    # Register the runner with GitHub
    if [ -f "/run/secrets/GITHUB_RUNNER_NAME_FILE" ]; then
        # Extract the name of the runner specified.
        GITHUB_RUNNER_NAME=$(cat /run/secrets/GITHUB_RUNNER_NAME_FILE)
        ./config.sh --unattended --url $GITHUB_REPO --token $TOKEN_VALUE --name $GITHUB_RUNNER_NAME
    else
        # Simply configure with the default name.
        ./config.sh --unattended --url $GITHUB_REPO --token $TOKEN_VALUE
    fi
fi

# Run the runner
./run.sh