name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yaml"
      - "**Dockerfile"
      - "**entrypoint"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/api.yaml"
      - "**Dockerfile"
      - "**entrypoint"

permissions:
  contents: read
  packages: write 

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      IMAGE_NAME: aldhinn/gh-self

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      id: docker_login
      uses: docker/login-action@v2
      with:
        username: aldhinn
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: true  # Continue even if login fails

    # Build the amd64 linux base image.
    - name: Build amd64 linux base image.
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:amd64-linux-base --build-arg \
        RUNNER_VERSION=2.320.0 --build-arg GH_PLATFORM=x64 linux

    # Conditionally push the amd64 linux base image only if login succeeded
    - name: Push amd64 linux base image.
      if: ${{ steps.docker_login.outcome == 'success' }}
      run: docker push ${{ env.IMAGE_NAME }}:amd64-linux-base

    # Build the amd64 debian image.
    - name: Build amd64 debian image.
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:amd64-debian --build-arg \
        BUNDLE_IMAGE=${{ env.IMAGE_NAME }}:amd64-linux-base debian

    # Conditionally push the amd64 linux base image only if login succeeded
    - name: Push amd64 debian image.
      if: ${{ steps.docker_login.outcome == 'success' }}
      run: docker push ${{ env.IMAGE_NAME }}:amd64-debian