name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yaml"
      - "**Dockerfile"
      - "**entrypoint"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/api.yaml"
      - "**Dockerfile"
      - "**entrypoint"

permissions:
  contents: read
  packages: write 

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      IMAGE_NAME: aldhinn/gh-self

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build amd64 linux base image.
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:amd64-linux-base --build-arg \
        RUNNER_VERSION=2.320.0 --build-arg GH_PLATFORM=x64 linux

    - name: Build amd64 debian image.
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:amd64-debian --build-arg \
        BUNDLE_IMAGE=${{ env.IMAGE_NAME }}:amd64-linux-base debian