name: publish

on:
  push:
    tags:
      - 'v*' # Triggers only for tags that start with "v"

jobs:
  login-to-docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: aldhinn
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-and-push:
    runs-on: self-hosted
    needs: login-to-docker

    env:
      IMAGE_NAME: aldhinn/gh-self
    
    steps:
      - name: Build amd64 linux base image.
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:amd64-linux-base --build-arg \
          RUNNER_VERSION=2.320.0 --build-arg GH_PLATFORM=x64 linux

      - name: Build amd64 debian image.
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:amd64-debian-${{ github.ref_name }} --build-arg \
          BUNDLE_IMAGE=${{ env.IMAGE_NAME }}:amd64-linux-base debian

      - name: Push amd64 debian image.
        run: docker push ${{ env.IMAGE_NAME }}:amd64-debian-${{ github.ref_name }}